name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
  workflow_dispatch:
 
jobs:
  buid-push-nogpu:
    name: "Build & push nogpu image"
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: docker/Dockerfile
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/robobase:nogpu

  buid-push-nvidia:
    name: "Build & push NVIDIA image"
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: docker/Dockerfile.nvidia
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/robobase:nvidia
